### ISSUE TITLE
FragmentBuilder - exception during macro expansion

### ISSUE THREAD

**Issue by akahanek** [47deg/macroid#89]
I use FragmentBuilder like this:

`f[MyFragment].pass("someId" -> someId).factory`

This works fine in 2.0.0-M4. After upgrade to 2.0.0-M5 a compilation error raises:

`[error] scala.MatchError: (macroid.FragmentBuilder.apply[my.package.MyFragment](macroid.Ui.apply[my.package.MyFragment](new my.package.MyFragment()), new android.os.Bundle())(TaskDetail.this.activityContextWrapper(scala.this.Predef.$conforms[android.support.v4.app.FragmentActivity]), support.this.Fragment.legacyFragment): macroid.FragmentBuilder[my.package.MyFragment]) (of class scala.reflect.internal.Trees$Typed)
[error]     at macroid.FragmentBuildingMacros.passImpl(FragmentBuilding.scala:92)
[error]                f[MyFragment].pass(("someId", someId)).factory`

I have changed my code to 

`val bundle = new Bundle();
bundle.putString("someId", someId);
f[MyFragment].pass(bundle).factory`

which works, but compared to "tuple version" code it is more verbose.
Is there any chance that I can use the "tuple version"? 
Thanks for any hints.
Ales

**Comment by javipacheco** [comment]
Hey @akahanek I agree with you, it's more verbose

We are working to create the 2.0 in the next week, maybe 2 weeks :-)

Could you create a new PR with this behaviour?

Thanks!

**Comment by fedefernandez** [comment]
Use `Bundles.bundle` macro instead:
`f[MyFragment].pass(Bundles.bundle("someId" -> someId)).factory`
